module.exports = {
    name: 'chance',
    description: "",
    execute(message, args) {
        message.delete();
            const chance = [
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost', 'You lost',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞', '😞 You lost 😞',
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢", "You did not win 😢 😢 😢",
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner',
                'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 'Not a winner', 
                '😂 😂 CONGRATULATIONS YOU WON THE GAME 😂 😂 please tell an admin and they will give you a special roll for winning'
                //there is a 1 in 1,000 chance of wining this game. the prize is a special role that just tells everyone that you won.

            ];
            const randomIndex = Math.floor(Math.random() * chance.length);

            const randomElement = chance[randomIndex];

            message.channel.send(`<@${message.author.id}> picked a ticket and it said: ${randomElement}`);//use "<@$
    }
    
}